import {CONFIG} from './config.js';
import {EventBus} from './events.js';
import {Storage} from './storage.js';
import {loadQuestions} from './questions.js';
import {Game} from './game.js';
import {AudioEngine} from './audio.js';
import {Effects} from './effects.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.round(n).toLocaleString('ja-JP'),sec=n=>(n/1000).toFixed(1),letters=['A','B','C','D'];
const bus=new EventBus(),db=new Storage(),game=new Game(bus),audio=new AudioEngine(toast),effects=new Effects($('#ambient'),audio);
let settings={...CONFIG.defaults},questions=[],sessions=[],dbReady=false,preparing=false,nextTimer,toastTimer,settingsTimer,currentView='home',previewing=false,settingsPaused=false,pendingResult=null,installPrompt=null;
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function view(name){currentView=name;$$('.view').forEach(e=>e.hidden=e.id!==name);$('#open-settings').hidden=name==='play';$('#brand').disabled=name==='play';window.scrollTo({top:0,behavior:'instant'});}
function applySettings(){audio.apply(settings);effects.apply(settings);$('#home-track').value=settings.track;$('#track-mood').textContent=CONFIG.tracks.find(t=>t.id===settings.track)?.mood||'';}
function updateHome(){const today=new Date().toLocaleDateString();const count=sessions.filter(s=>new Date(s.date).toLocaleDateString()===today).reduce((a,s)=>a+s.correct,0);$('#today-correct').innerHTML=`${count}<small>問</small>`;const five=sessions.filter(s=>s.count===5);$('#home-best').textContent=five.length?fmt(Math.max(...five.map(s=>s.score))):'—';$('#home-combo').textContent=sessions.length?Math.max(...sessions.map(s=>s.maxCombo)):'—';}
async function storageInfo(request=false,notify=false){const status=await db.persistence(request);$('#storage-status').textContent={'granted':'● 永続化：許可済み','denied':'○ 永続化：未許可（通常保存は利用可能）','unsupported':'このブラウザは永続化申請に非対応'}[status];$('#request-persist').hidden=status==='granted'||status==='unsupported';const bytes=new Blob([JSON.stringify(sessions)]).size;$('#storage-size').textContent=`${sessions.length}プレイ · 履歴データ 約${(bytes/1024).toFixed(1)} KB`;if(notify&&status==='granted')toast('この端末で永続化が許可されました');}
function setPreview(value){previewing=value;$('#preview-track').textContent=value?'Ⅱ':'▷';$('#preview-track').setAttribute('aria-label',value?'試聴を停止':'BGMを試聴');}
function showReward(tier){const r=$('#reward');r.textContent=tier.label;r.style.color=tier.color;r.classList.remove('fire');requestAnimationFrame(()=>r.classList.add('fire'));effects.burst(tier);}
function scheduleNext(delay){clearTimeout(nextTimer);nextTimer=setTimeout(()=>game.next(),delay);}
async function start(count){if(preparing||!questions.length)return;preparing=true;$$('.start').forEach(b=>b.disabled=true);try{if(pendingResult&&dbReady){try{await db.write('sessions',pendingResult);sessions.push(pendingResult);pendingResult=null;}catch{toast('前回の履歴を保存できませんでした。結果画面から再試行してください');return;}}
 setPreview(false);audio.stop();try{await audio.init();await audio.preload();}catch{toast('音声を開始できませんでした。音なしで続けます');}applySettings();void audio.playTrack(settings.track);view('play');game.start(questions,count);void storageInfo(true);
 }finally{preparing=false;$$('.start').forEach(b=>b.disabled=false);}}
bus.on('question',({question:q,index,total})=>{
 $('#question-progress').textContent=`${String(index+1).padStart(2,'0')} / ${String(total).padStart(2,'0')}`;$('#progress-bar').style.width=`${index/total*100}%`;$('#question-category').textContent=q.category;$('#question-text').innerHTML=escape(q.text).replace('_____','<span class="blank" aria-label="空欄">&nbsp;?&nbsp;</span>');$('#choices').replaceChildren();q.options.forEach((option,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<span class="choice-letter">${letters[i]}</span><span lang="en">${escape(option)}</span>`;b.onclick=()=>game.answer(i);$('#choices').append(b);});$('#feedback').textContent='';$('#feedback').className='feedback';$('#combo-number').textContent=game.combo;$('#play-score').innerHTML=`${fmt(game.score)} <small>PTS</small>`;if(index===0)$('#combo-tier').textContent='LET’S GO';
});
bus.on('answer',data=>{const {question:q,choice,correct,tier,points,score,combo}=data;$$('.choice').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');if(!correct&&i===choice)b.classList.add('wrong');});$('#combo-number').textContent=combo;$('#combo-tier').textContent=correct?tier.label:'NEXT CHANCE';$('#combo-tier').style.color=tier.color;$('#play-score').innerHTML=`${fmt(score)} <small>PTS</small>`;$('#progress-bar').style.width=`${(game.index+1)/game.questions.length*100}%`;$('#feedback').textContent=correct?`✓ 正解！ +${fmt(points)}`:`正解：${letters[q.answer]}. ${q.options[q.answer]}`;$('#feedback').classList.toggle('wrong',!correct);if(correct){audio.sound(data.feverStarted?'FEVER':tier.label==='FEVER'?'PERFECT':tier.label);showReward(tier);}else audio.sound('WRONG');scheduleNext(correct?CONFIG.transitions.correct:CONFIG.transitions.incorrect);});
bus.on('fever:start',()=>{effects.fever=true;document.body.classList.add('fever');$('#fever-time').hidden=false;});bus.on('fever:end',()=>{effects.fever=false;document.body.classList.remove('fever');$('#fever-time').hidden=true;});
bus.on('finish',async result=>{audio.stop();const same=sessions.filter(s=>s.count===result.count&&s.mode===result.mode);const best=same.length?Math.max(...same.map(s=>s.score)):0;result.newRecord=result.score>best;pendingResult=result;renderResult(result,true);if(result.newRecord){setTimeout(()=>{if(currentView==='result'){audio.sound('RECORD');effects.burst({color:'#ffe1a2'},true);}},120);}try{if(!dbReady)throw Error();await db.write('sessions',result);sessions.push(result);pendingResult=null;const e=$('#save-message');if(e)e.textContent='✓ この端末に保存済み';updateHome();}catch{const e=$('#save-message');if(e)e.innerHTML='履歴を保存できませんでした。<button class="small-button" id="retry-save">保存を再試行</button>';$('#retry-save')?.addEventListener('click',retrySave);}});
async function retrySave(){if(!pendingResult)return;try{if(!dbReady){await db.open();dbReady=true;sessions=await db.read('sessions');}await db.write('sessions',pendingResult);sessions=sessions.filter(s=>s.id!==pendingResult.id);sessions.push(pendingResult);pendingResult=null;$('#save-message').textContent='✓ この端末に保存済み';updateHome();}catch{toast('保存できませんでした。端末の空き容量をご確認ください');}}
function reviewMarkup(a,i){const q=a.question;return `<details class="review-item ${a.correct?'':'missed'}"><summary><span class="status">${a.correct?'✓':'×'}</span><span>Q${i+1} · ${escape(q.category)} <span class="tiny">${sec(a.ms)}秒</span></span></summary><div class="review-body"><p class="english" lang="en">${escape(q.text).replace('_____',`<em>${escape(q.options[q.answer])}</em>`)}</p><p class="answer-line">正解：${letters[q.answer]}. ${escape(q.options[q.answer])}</p><p class="${a.correct?'':'your-answer'}">あなたの回答：${letters[a.choice]}. ${escape(q.options[a.choice])}</p><p>${escape(q.translation)}</p><p>${escape(q.explanation)}</p><span class="tag">${escape(q.category)} · 難易度 ${q.difficulty===1?'基礎':'標準'}</span></div></details>`;}
function renderResult(r,fresh=false){view('result');const pct=Math.round(r.accuracy*100),title=pct===100?'PERFECT!':pct>=80?'GREAT!':pct>=60?'GOOD JOB!':'NICE TRY!';$('#result').innerHTML=`<div class="section-top"><button class="text-button back-home">← トップ</button><span class="micro">${fresh?'SESSION COMPLETE':'PLAYBACK'}</span></div><div class="result-hero"><div class="result-label">${title}</div><div class="result-fraction">${r.correct} <span>/ ${r.count}</span></div><p>正答率 ${pct}% · ${pct===100?'全問正解。この調子！':'ひとつずつ、できるを増やそう。'}</p>${r.newRecord?'<div class="record-badge">✦ NEW RECORD</div>':''}</div><div class="result-stats"><div><span>SCORE</span><strong>${fmt(r.score)}</strong></div><div><span>MAX COMBO</span><strong>${r.maxCombo}</strong></div><div><span>平均回答時間</span><strong>${sec(r.avgMs)} <small>秒</small></strong></div><div><span>正解時の平均</span><strong>${r.correctAvgMs===null?'—':sec(r.correctAvgMs)} <small>秒</small></strong></div></div><div class="result-actions"><button class="primary start" data-count="5">もう5問、遊ぼう ↗</button><button class="secondary start" data-count="10">10問でFEVERを狙う ⚡</button></div><p class="tiny center" id="save-message">${fresh?'履歴を保存中…':'✓ この端末に保存済み'}</p><h2 class="review-heading">答えを振り返る <small>間違い ${r.count-r.correct}問 · タップで解説</small></h2>${r.answers.map(reviewMarkup).join('')}`;bindNavigation();}
function showHistory(){audio.stop();setPreview(false);view('history');let html='';if(!sessions.length)html='<div class="empty">最初の5問から、はじめよう。<br>プレイするとここに記録が残るよ。</div>';else{const categories={};for(const s of sessions)for(const a of s.answers){const c=categories[a.question.category]??={total:0,correct:0};c.total++;c.correct+=Number(a.correct);}html=`<h3>カテゴリ別の正答率</h3>${Object.entries(categories).map(([k,v])=>`<div class="category-row"><span>${escape(k)}</span><span>${Math.round(v.correct/v.total*100)}% <small>(${v.correct}/${v.total})</small></span></div>`).join('')}<h3>これまでのプレイ</h3>`;html+=[...sessions].sort((a,b)=>b.date.localeCompare(a.date)).map(s=>`<button class="history-row" data-session="${escape(s.id)}"><span>${new Date(s.date).toLocaleString('ja-JP',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}<small>${s.count}問 · ${Math.round(s.accuracy*100)}% · ${sec(s.avgMs)}秒</small></span><span><strong>${s.correct}/${s.count}</strong><small>${fmt(s.score)} PTS →</small></span></button>`).join('');}$('#history-content').innerHTML=html;$$('[data-session]').forEach(b=>b.onclick=()=>renderResult(sessions.find(s=>s.id===b.dataset.session)));}
function home(){clearTimeout(nextTimer);game.stop();audio.stop();setPreview(false);updateHome();view('home');}
function bindNavigation(){$$('.start').forEach(b=>b.onclick=()=>start(Number(b.dataset.count)));$$('.back-home').forEach(b=>b.onclick=home);}
function pauseGame(show=true){if(!['playing','feedback'].includes(game.state))return;clearTimeout(nextTimer);game.pause();void audio.suspend();if(show&&!$('#pause-dialog').open)$('#pause-dialog').showModal();}
async function resumeGame(){try{await audio.init();}catch{}game.resume();if(game.state==='feedback')scheduleNext(500);if($('#pause-dialog').open)$('#pause-dialog').close();}
$('#pause').onclick=()=>pauseGame();$('#resume').onclick=resumeGame;$('#pause-dialog').addEventListener('cancel',e=>{e.preventDefault();void resumeGame();});$('#exit-game').onclick=()=>{$('#pause-dialog').close();home();};document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseGame();if(game.state==='idle'||game.state==='finished'){audio.stop();setPreview(false);}}});
$('#brand').onclick=home;$('#open-history').onclick=showHistory;
$('#preview-track').onclick=async()=>{if(previewing){audio.stop();setPreview(false);return;}try{await audio.init();if(!settings.bgm){settings.bgm=true;applySettings();void saveSettings();}setPreview(true);await audio.playTrack(settings.track);}catch{toast('BGMを再生できませんでした');setPreview(false);}};
$('#home-track').onchange=async e=>{settings.track=e.target.value;applySettings();void saveSettings();if(previewing)await audio.playTrack(settings.track);};
async function saveSettings(){if(!dbReady)return;try{await db.write('settings',settings,'preferences');}catch{toast('設定を保存できませんでした');}}
$('#open-settings').onclick=()=>{settingsPaused=['playing','feedback'].includes(game.state);if(settingsPaused)pauseGame(false);const f=$('#settings-form');for(const[k,v]of Object.entries(settings)){if(!f.elements[k])continue;if(typeof v==='boolean')f.elements[k].checked=v;else f.elements[k].value=v;}$('#bgm-volume-value').value=`${Math.round(settings.bgmVolume*100)}%`;$('#se-volume-value').value=`${Math.round(settings.seVolume*100)}%`;void storageInfo();$('#settings-dialog').showModal();};
$('#close-settings').onclick=()=>$('#settings-dialog').close();$('#settings-dialog').addEventListener('close',()=>{if(settingsPaused){settingsPaused=false;void resumeGame();}});
$('#settings-form').onsubmit=e=>e.preventDefault();$('#settings-form').addEventListener('input',e=>{const input=e.target,k=input.name;if(!(k in CONFIG.defaults))return;const previous=settings[k];settings[k]=input.type==='checkbox'?input.checked:input.type==='range'?Number(input.value):input.value;applySettings();$('#bgm-volume-value').value=`${Math.round(settings.bgmVolume*100)}%`;$('#se-volume-value').value=`${Math.round(settings.seVolume*100)}%`;clearTimeout(settingsTimer);settingsTimer=setTimeout(saveSettings,150);if(k==='track'&&previewing&&previous!==settings[k])void audio.playTrack(settings.track);if(k==='bgm'&&!settings.bgm){audio.stop();setPreview(false);}});
$('#test-se').onclick=async()=>{try{await audio.init();await audio.preload();audio.sound('PERFECT');}catch{toast('効果音を再生できませんでした');}};$('#request-persist').onclick=()=>storageInfo(true,true);
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-app').hidden=false;});$('#install-app').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install-app').hidden=true;void storageInfo(true);}};
setInterval(()=>{if(game.state!=='playing'&&game.state!=='feedback')return;game.tick();if(game.state==='playing')$('#elapsed').textContent=`${sec(performance.now()-game.questionStart)} sec`;if(game.fever)$('#fever-time span').textContent=Math.max(0,(game.feverUntil-performance.now())/1000).toFixed(0);},100);
async function init(){for(const sel of [$('#home-track'),$('#settings-form').elements.track]){sel.innerHTML=CONFIG.tracks.map(t=>`<option value="${t.id}">${t.title}</option>`).join('');}$$('.start').forEach(b=>b.disabled=true);try{await db.open();dbReady=true;const saved=await db.read('settings','preferences');if(saved){for(const[k,v]of Object.entries(CONFIG.defaults)){const n=saved[k];if(typeof n===typeof v)settings[k]=n;}if(!CONFIG.tracks.some(t=>t.id===settings.track))settings.track=CONFIG.defaults.track;if(!['LOW','NORMAL','HIGH'].includes(settings.effects))settings.effects='HIGH';settings.bgmVolume=Math.max(0,Math.min(1,settings.bgmVolume));settings.seVolume=Math.max(0,Math.min(1,settings.seVolume));}sessions=await db.read('sessions');}catch{toast('端末の保存領域を開けませんでした。履歴は保存できない状態です');}applySettings();updateHome();bindNavigation();try{questions=await loadQuestions();$('#question-count').textContent=`${questions.length}問収録 · 端末に履歴保存`;$$('.start').forEach(b=>b.disabled=false);}catch(e){$('#question-count').textContent='問題を読み込めませんでした';toast(e.message);}
 if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').catch(()=>toast('オフライン準備を完了できませんでした'));}void storageInfo();}
void init();
