import {CONFIG} from './config.js';
export class AudioEngine {
 constructor(onError=()=>{}){this.onError=onError;this.buffers=new Map();this.active=false;this.settings={...CONFIG.defaults};this.loadId=0;}
 async init(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('このブラウザでは音声が利用できません');this.ctx=new AC({latencyHint:'interactive'});const c=this.ctx;this.master=c.createDynamicsCompressor();this.master.threshold.value=-3;this.master.knee.value=6;this.master.ratio.value=12;this.master.attack.value=.003;this.master.release.value=.12;this.master.connect(c.destination);this.music=c.createGain();this.analyser=c.createAnalyser();this.analyser.fftSize=256;this.analyser.smoothingTimeConstant=.8;this.music.connect(this.analyser);this.analyser.connect(this.master);this.se=c.createGain();this.se.connect(this.master);this.frequency=new Uint8Array(this.analyser.frequencyBinCount);this.wave=new Uint8Array(this.analyser.fftSize);this.apply(this.settings);}
 await this.ctx.resume();}
 async preload(){if(this.preloading)return this.preloading;this.preloading=Promise.all(Object.entries(CONFIG.seFiles).map(async([key,file])=>{try{const r=await fetch(`assets/se/${file}.wav`);if(!r.ok)throw Error();this.buffers.set(key,await this.ctx.decodeAudioData(await r.arrayBuffer()));}catch{this.onError('一部の効果音を読み込めませんでした');}}));return this.preloading;}
 apply(settings){this.settings={...settings};if(!this.ctx)return;const t=this.ctx.currentTime;this.music.gain.cancelScheduledValues(t);this.music.gain.setTargetAtTime(settings.bgm?settings.bgmVolume*.7:0,t,.04);this.se.gain.setTargetAtTime(settings.se?settings.seVolume*.8:0,t,.015);}
 async playTrack(id){this.active=true;const serial=++this.loadId;this.stopSource();if(!this.settings.bgm||!this.ctx)return;const track=CONFIG.tracks.find(t=>t.id===id)||CONFIG.tracks[0];try{if(this.trackId!==track.id||!this.trackBuffer){const r=await fetch(track.file);if(!r.ok)throw Error();const buffer=await this.ctx.decodeAudioData(await r.arrayBuffer());if(serial!==this.loadId||!this.active)return;for(let ch=0;ch<buffer.numberOfChannels;ch++){const a=buffer.getChannelData(ch),n=Math.min(Math.floor(buffer.sampleRate*.005),Math.floor(a.length/2));for(let i=0;i<n;i++){a[i]*=i/n;a[a.length-1-i]*=i/n;}}this.trackBuffer=buffer;this.trackId=track.id;}if(serial!==this.loadId||!this.active)return;const source=this.ctx.createBufferSource(),fade=this.ctx.createGain();source.buffer=this.trackBuffer;source.loop=true;fade.gain.setValueAtTime(0,this.ctx.currentTime);fade.gain.linearRampToValueAtTime(1,this.ctx.currentTime+.06);source.connect(fade);fade.connect(this.music);source.start();this.source=source;this.fade=fade;}catch{this.onError('BGMを再生できませんでした。設定からもう一度選んでください');}}
 stopSource(){if(!this.source)return;const s=this.source,f=this.fade,t=this.ctx.currentTime;f.gain.cancelScheduledValues(t);f.gain.setTargetAtTime(0,t,.012);try{s.stop(t+.06);}catch{}s.onended=()=>{s.disconnect();f.disconnect();};this.source=null;}
 stop(){this.active=false;this.loadId++;this.stopSource();}
 sound(key){if(!this.ctx||!this.settings.se)return;const buffer=this.buffers.get(key);if(!buffer)return;const s=this.ctx.createBufferSource();s.buffer=buffer;s.connect(this.se);s.start();s.onended=()=>s.disconnect();const t=this.ctx.currentTime,g=this.music.gain,target=this.settings.bgm?this.settings.bgmVolume*.7:0;g.cancelScheduledValues(t);g.setTargetAtTime(target*Math.pow(10,CONFIG.audio.duckDb/20),t,.012);g.setTargetAtTime(target,t+.09,CONFIG.audio.duckRelease/3);}
 levels(){if(!this.analyser)return {bass:0,mid:0,treble:0,wave:null};this.analyser.getByteFrequencyData(this.frequency);this.analyser.getByteTimeDomainData(this.wave);const mean=(a,b)=>{let n=0;for(let i=a;i<b;i++)n+=this.frequency[i];return n/((b-a)*255);};return{bass:mean(0,5),mid:mean(5,35),treble:mean(35,100),wave:this.wave};}
 async suspend(){if(this.ctx)await this.ctx.suspend();}
}
