import {CONFIG} from './config.js';
export class Effects {
 constructor(canvas,audio){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.audio=audio;this.settings=CONFIG.defaults;this.particles=[];this.fever=false;this.pulse=0;this.color='#61f3d5';this.last=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.resize=()=>{this.w=innerWidth;this.h=innerHeight;const d=Math.min(devicePixelRatio||1,1.5);canvas.width=this.w*d;canvas.height=this.h*d;this.ctx.setTransform(d,0,0,d,0,0);};addEventListener('resize',this.resize);this.resize();requestAnimationFrame(t=>this.frame(t));}
 apply(s){this.settings=s;}
 burst(tier,record=false){this.color=tier.color;this.pulse=1;const count=this.reduced?0:CONFIG.visual.particles[this.settings.effects]*(record?1.5:1);for(let i=0;i<count&&this.particles.length<CONFIG.visual.maxParticles;i++){const a=Math.random()*Math.PI*2,v=2+Math.random()*7;this.particles.push({x:this.w/2,y:this.h*.43,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:1,size:1+Math.random()*3,color:tier.color});}}
 frame(t){requestAnimationFrame(n=>this.frame(n));if(document.hidden||t-this.last<1000/CONFIG.visual.fps)return;const dt=Math.min((t-this.last)/33.3,2)||1;this.last=t;const c=this.ctx,w=this.w,h=this.h;c.clearRect(0,0,w,h);const enabled=this.settings.background&&!this.reduced;const level=enabled?this.audio.levels():{bass:0,mid:0,treble:0,wave:null};
 if(enabled){const glow=c.createRadialGradient(w*.5,h*.35,5,w*.5,h*.35,w*.8);glow.addColorStop(0,this.fever?`rgba(232,152,54,${.07+level.bass*.15})`:`rgba(41,211,191,${.03+level.bass*.1})`);glow.addColorStop(1,'transparent');c.fillStyle=glow;c.fillRect(0,0,w,h);
 const y=h*.64;c.strokeStyle=this.fever?'#dca653':'#39c6c0';c.lineWidth=1.2;c.globalAlpha=.14+level.mid*.2;c.beginPath();for(let i=0;i<45;i++){const x=i*w/44,v=level.wave?((level.wave[Math.floor(i*level.wave.length/45)]-128)/128):0;const z=y+v*(24+level.mid*65)+Math.sin(i*.3+t*.0008)*10;if(i===0)c.moveTo(x,z);else c.lineTo(x,z);}if(this.settings.waveform)c.stroke();c.globalAlpha=1;
 if(this.settings.waveform){const bars=32,bw=Math.min(8,w/80),gap=5,start=(w-bars*(bw+gap))/2;c.fillStyle=this.fever?'#e8bd72':'#60e5da';for(let i=0;i<bars;i++){const f=this.audio.frequency?.[i*2]||0,bh=3+f/255*40;c.globalAlpha=.16+f/255*.18;c.fillRect(start+i*(bw+gap),h-55-bh,bw,bh);}c.globalAlpha=1;}}
 if(this.pulse>.01){c.globalAlpha=this.pulse*(this.settings.effects==='LOW'?.13:.24);c.strokeStyle=this.color;c.lineWidth=2+this.pulse*8;c.strokeRect(3,3,w-6,h-6);c.globalAlpha=1;this.pulse*=Math.pow(.86,dt);}
 for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.09*dt;p.life-=.028*dt;if(p.life<=0){this.particles.splice(i,1);continue;}c.globalAlpha=p.life;c.fillStyle=p.color;c.fillRect(p.x,p.y,p.size,p.size*2);}c.globalAlpha=1;
 }
}
